### ISSUE TITLE
Finding about "nto_hack_2022/V2/v2_1.pt"

### ISSUE THREAD

**Issue by rvssridatta** [KARTASAR/video-captioning#1]
Hi @KARTASAR

It was great work on video captioning. I like to know about weights in this link. Based on your feasibility is that possible to share the weights or any alternative solutions to replace them (without training the model just I am looking for inferencing the model)
![image](https://github.com/KARTASAR/video-captioning/assets/65171912/2d66d76f-4f0c-4e10-8083-dfd9e39f7421)
And also which data you have used for training. 
how to produce this train_features_path?
![image](https://github.com/KARTASAR/video-captioning/assets/65171912/17bf284f-d569-47e8-bc36-1c3dc14c56f3)

**Comment by KARTASAR** [comment]
Hi!
Here are the weights for the model: https://drive.google.com/file/d/1zlwdbdSA14Iiptw4GUjEgj8IlFRmH03j/view?usp=sharing

As for Features_train.pkl, you can get it with preprocess.ipynb notebook.

**Comment by rvssridatta** [comment]
Thanks @KARTASAR for sharing the info.
